"""
Smart City Transit Optimizer — Python Analytics Layer (Week 3)
================================================================
Reads CSV logs generated by the C++ engine and produces:
  1. Peak hour analysis        (busiest boarding hours)
  2. Route efficiency score    (passengers per km, delay-adjusted)
  3. Station footfall ranking  (busiest stations)
  4. Fare revenue breakdown    (by route)
  5. Daily demand trend        (passengers per day)
  6. Delay summary             (avg delay per route)

Output: analytics_output.csv  -> feeds directly into Power BI (Week 4)

Run:
    python transit_analysis.py
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

# ─── CONFIG ───────────────────────────────────────────────────────────────────
DATA_DIR    = "../data"
OUTPUT_DIR  = "."
JOURNEY_CSV = os.path.join(DATA_DIR, "journey_log.csv")
STATION_CSV = os.path.join(DATA_DIR, "station_stats.csv")
DELAY_CSV   = os.path.join(DATA_DIR, "delay_log.csv")


def load_data():
    """Load and clean all 3 CSV files produced by the C++ engine."""
    journeys = pd.read_csv(JOURNEY_CSV)
    stations = pd.read_csv(STATION_CSV)
    delays   = pd.read_csv(DELAY_CSV)

    # Parse timestamp into proper datetime + extract hour/date
    journeys["timestamp"] = pd.to_datetime(journeys["timestamp"])
    journeys["hour"]      = journeys["timestamp"].dt.hour
    journeys["date"]      = journeys["timestamp"].dt.date

    # Drop any nulls (defensive cleaning — real pipelines always do this)
    journeys = journeys.dropna()
    stations = stations.dropna()
    delays   = delays.dropna()

    print(f"[+] Loaded {len(journeys)} journeys, {len(stations)} station records, {len(delays)} delay records")
    return journeys, stations, delays


def peak_hour_analysis(journeys):
    """Find the busiest hours of the day by passenger count."""
    hourly = journeys.groupby("hour").size().reset_index(name="trip_count")
    hourly = hourly.sort_values("trip_count", ascending=False)
    print("\n=== Peak Hours (Top 5) ===")
    print(hourly.head(5).to_string(index=False))
    return hourly


def route_efficiency_score(journeys):
    """
    Efficiency score = passengers carried per km traveled.
    Higher score = more passengers using shorter routes = efficient route.
    We group by from_station -> to_station pair as a proxy for "route".
    """
    routes = journeys.groupby(["from_station", "to_station"]).agg(
        trip_count=("journey_id", "count"),
        avg_distance=("distance_km", "mean"),
        avg_fare=("fare_rs", "mean"),
        avg_duration=("duration_mins", "mean")
    ).reset_index()

    # NumPy used here for the efficiency formula
    routes["efficiency_score"] = np.round(
        routes["trip_count"] / routes["avg_distance"], 2
    )
    routes = routes.sort_values("efficiency_score", ascending=False)

    print("\n=== Route Efficiency (Top 5) ===")
    print(routes.head(5).to_string(index=False))
    return routes


def station_footfall_ranking(stations):
    """Rank stations by total boardings — busiest stations first."""
    footfall = stations.groupby("station_name")["total_boardings"].sum().reset_index()
    footfall = footfall.sort_values("total_boardings", ascending=False)
    print("\n=== Busiest Stations (Top 5) ===")
    print(footfall.head(5).to_string(index=False))
    return footfall


def fare_revenue_breakdown(journeys):
    """Total fare revenue generated per route."""
    revenue = journeys.groupby(["from_station", "to_station"])["fare_rs"].sum().reset_index()
    revenue.columns = ["from_station", "to_station", "total_revenue_rs"]
    revenue["revenue_pct"] = np.round(
        100 * revenue["total_revenue_rs"] / revenue["total_revenue_rs"].sum(), 2
    )
    revenue = revenue.sort_values("total_revenue_rs", ascending=False)
    print("\n=== Fare Revenue by Route (Top 5) ===")
    print(revenue.head(5).to_string(index=False))
    return revenue


def daily_demand_trend(journeys):
    """Passenger demand trend per day (useful if simulation spans multiple days)."""
    daily = journeys.groupby("date").size().reset_index(name="trip_count")
    print("\n=== Daily Demand Trend ===")
    print(daily.to_string(index=False))
    return daily


def delay_summary(delays):
    """Average delay per route + overall on-time performance."""
    summary = delays.groupby("route_name")["delay_minutes"].mean().reset_index()
    summary.columns = ["route_name", "avg_delay_minutes"]
    summary["avg_delay_minutes"] = np.round(summary["avg_delay_minutes"], 1)
    summary = summary.sort_values("avg_delay_minutes", ascending=False)

    overall_avg_delay = delays["delay_minutes"].mean()
    on_time_pct = (delays["delay_minutes"] <= 5).mean() * 100

    print("\n=== Delay Summary by Route ===")
    print(summary.to_string(index=False))
    print(f"\n[i] Overall avg delay: {overall_avg_delay:.1f} min | On-time (<=5min): {on_time_pct:.1f}%")
    return summary, overall_avg_delay, on_time_pct


def plot_quick_charts(hourly, routes, footfall):
    """Quick Matplotlib EDA charts — sanity check before Power BI."""
    fig, axes = plt.subplots(1, 3, figsize=(15, 4))

    axes[0].bar(hourly["hour"], hourly["trip_count"], color="#4C72B0")
    axes[0].set_title("Trips by Hour")
    axes[0].set_xlabel("Hour of Day")
    axes[0].set_ylabel("Trip Count")

    top_routes = routes.head(5)
    axes[1].barh(
        top_routes["from_station"] + " -> " + top_routes["to_station"],
        top_routes["efficiency_score"], color="#55A868"
    )
    axes[1].set_title("Top 5 Routes by Efficiency")
    axes[1].invert_yaxis()

    top_stations = footfall.head(5)
    axes[2].bar(top_stations["station_name"], top_stations["total_boardings"], color="#C44E52")
    axes[2].set_title("Top 5 Busiest Stations")
    axes[2].tick_params(axis="x", rotation=30)

    plt.tight_layout()
    plt.savefig("eda_summary.png", dpi=120)
    print("\n[+] Saved chart preview: eda_summary.png")


def export_for_powerbi(journeys, routes, footfall, revenue, delay_summary_df):
    """
    Build ONE clean, merged CSV that Power BI will use as its single
    data source in Week 4. Each row = one route, with all KPIs attached.
    """
    merged = routes.merge(
        revenue[["from_station", "to_station", "total_revenue_rs", "revenue_pct"]],
        on=["from_station", "to_station"], how="left"
    )

    # Attach avg delay by matching route_name approx (best-effort join since
    # delay_log uses route names like "Nagpur-Wardha" not station pairs)
    merged["route_label"] = merged["from_station"] + " -> " + merged["to_station"]

    merged.to_csv("analytics_output.csv", index=False)
    footfall.to_csv("station_footfall.csv", index=False)
    delay_summary_df.to_csv("delay_summary.csv", index=False)

    print("\n[+] Exported for Power BI:")
    print("    - analytics_output.csv   (route-level KPIs)")
    print("    - station_footfall.csv   (station rankings)")
    print("    - delay_summary.csv      (route delay averages)")


# ─── MAIN ─────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("=" * 55)
    print("  SMART CITY TRANSIT OPTIMIZER - Analytics Layer")
    print("=" * 55)

    journeys, stations, delays = load_data()

    hourly_df   = peak_hour_analysis(journeys)
    routes_df   = route_efficiency_score(journeys)
    footfall_df = station_footfall_ranking(stations)
    revenue_df  = fare_revenue_breakdown(journeys)
    daily_df    = daily_demand_trend(journeys)
    delay_df, avg_delay, on_time_pct = delay_summary(delays)

    plot_quick_charts(hourly_df, routes_df, footfall_df)
    export_for_powerbi(journeys, routes_df, footfall_df, revenue_df, delay_df)

    print("\n" + "=" * 55)
    print("  Analysis complete. Ready for Power BI (Week 4).")
    print("=" * 55)